[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "imm"
description = "ImMatch (IMM): A versatile library for image matching and feature extraction."
authors = [{ name = "BOUAMER Tarek", email = "tarekbouamer1788@gmail.com" }]
license = { file = "LICENSE" }
requires-python = ">=3.8"


dynamic = ["readme", "version", "dependencies"]

[tool.setuptools.packages.find]
include = ["imm*"]

[tool.setuptools.dynamic]
version = { attr = "imm.__version__" }
readme = { file = "README.md" }
dependencies = { file = "requirements.txt" }

[project.urls]
Homepage = "https://github.com/Tarekbouamer/imm"
Documentation = "https://github.com/Tarekbouamer/imm/wiki"
Source = "https://github.com/Tarekbouamer/imm"
Tracker = "https://github.com/Tarekbouamer/imm/issues"

[project.entry-points.console_scripts]
imm-match = "imm.cli._match:cli"
imm-extract = "imm.cli._extract:cli"
imm-estimate = "imm.cli._estimate:cli"
imm-gui = "imm.ui:main"
imm-download = "imm.cli._download:download"
imm-export = "imm.cli._export:export"
imm-optimize = "imm.cli._optimize:cli"

[project.optional-dependencies]
extra = [
]
dev = ["black>=22.0", "flake8>=4.0", "isort>=5.0"]
docs = ["sphinx>=4.0", "sphinx-rtd-theme>=0.5"]
test = ["pytest>=6.0", "pytest-cov>=3.0", "tox>=3.0"]

[tool.ruff]
fix = true

[tool.ruff.isort]
profile = "black"
combine_as_imports = true
force_sort_within_sections = true
